=== CGB145/xml/kontakte.dtd
<?xml version="1.0" encoding="UTF-8"?>

	<!ELEMENT root (kontakt*)>
	
	<!ELEMENT kontakt (anrede,titel,name, vorname,spitzname,geburtstag,bild,firma*,adresse,nummern,mailadresse,webadresse,messenger,memo*,ereignisse, gruppen)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT vorname (#PCDATA)>
	<!ELEMENT titel (#PCDATA)>
	<!ELEMENT anrede (#PCDATA)>
	<!ELEMENT spitzname (#PCDATA)>
	<!ELEMENT geburtstag (#PCDATA)>
	<!ATTLIST geburtstag art CDATA #IMPLIED>
	<!ELEMENT mailadresse (#PCDATA)>
	<!ATTLIST mailadresse art CDATA #IMPLIED>
	<!ELEMENT webadresse (#PCDATA)>
	<!ATTLIST webadresse art CDATA #IMPLIED>
	<!ELEMENT messenger (#PCDATA)>
	<!ELEMENT bild EMPTY>
	<!-- Def. des Attributes "quelle" Element Bild -->
	<!ATTLIST bild quelle CDATA #IMPLIED >


	<!ELEMENT firma (name,abteilung,position)>
	<!ELEMENT abteilung (#PCDATA)>
	<!ELEMENT position (#PCDATA)>

	<!ELEMENT adresse (strasse,plz,ort,region,staat)>
	<!ELEMENT strasse (#PCDATA)>
	<!ELEMENT plz (#PCDATA)>
	<!ELEMENT ort (#PCDATA)>
	<!ELEMENT region (#PCDATA)>
	<!ELEMENT staat (#PCDATA)>

	<!ELEMENT nummern (nummer*)>
	<!ATTLIST nummern art CDATA #IMPLIED>
	<!ELEMENT nummer (#PCDATA)>
	<!ATTLIST nummer art CDATA #IMPLIED>
	<!ATTLIST nummer ton CDATA #IMPLIED>

	<!ELEMENT memo (notiz)>
	<!ELEMENT notiz (#PCDATA)>

	<!ELEMENT ereignisse (ereigniss*)>
	<!ELEMENT ereigniss (datum, bezeichnung, notiz)>
	<!ELEMENT datum (#PCDATA)>
	<!ELEMENT bezeichnung (#PCDATA)>

	<!ELEMENT gruppen (gruppe)>
	<!ELEMENT gruppe (#PCDATA)>









	<!-- Multiplaktoren
		min	max
	NULL	1	1
	? 	0 	1
	+ 	1 	unendlich
	* 	0 	unendlich



	-->

=== CGB145/xml/Tag-2-Oder-So.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE root SYSTEM "kontakte.dtd">
<root>
	
	<kontakt>

		<anrede></anrede>
		<titel></titel>
		<name> Meier </name>
		<vorname> Franziska </vorname>
		<spitzname> Franzi </spitzname>
		<geburtstag> 22.07.2001 </geburtstag>
		<bild quelle="P1234567.jpg" />

		<adresse>
			<strasse> Tulpenweg 18 </strasse>
			<plz> 84321 </plz>
			<ort> Hinterhausen </ort>
			<region> </region>
			<staat> </staat>
		</adresse>

		<nummern> 
			<nummer art="privat"> 0891234564 </nummer>
			<nummer art="mobil" ton="Basic Bell"> 017623456789 </nummer>
		</nummern>
		
		<mailadresse art="privat"> franzi@web.de </mailadresse>
		<webadresse> </webadresse>
		<messenger> </messenger>

		<ereignisse>
			<ereigniss>
				<datum> 15.11 </datum>
				<bezeichnung> treffen </bezeichnung>
				<notiz> </notiz>
			</ereigniss>
		</ereignisse>

		<gruppen>
			<gruppe> Freunde </gruppe>
		</gruppen>
		
	</kontakt>

	<kontakt>

		<anrede> Herr </anrede>
		<titel></titel>
		<name> Bayramoglu </name>
		<vorname> Caglan </vorname>
		<spitzname></spitzname>
		<geburtstag> 13.01.2003 </geburtstag>
		<bild/> 

		<firma> 
			<name> </name>
			<abteilung> </abteilung>
			<position> </position>
		</firma>	

		<adresse>
			<strasse> Rosenheimer Str.80 </strasse>
			<plz> 81669 </plz>
			<ort> München </ort>
			<region> Bayern </region>
			<staat> Deutschland </staat>
		</adresse>

		<nummern> 
			<nummer art="privat"> 01727966864</nummer>
		</nummern>
		
		<mailadresse art="privat"> b.caglan@outlook.com </mailadresse>
		<webadresse art="privat"> cgb145.github.io </webadresse>
		<messenger> </messenger>

		<memo>
			<notiz> ich </notiz>
		</memo>

		<ereignisse>
			<ereigniss>
				<datum> 26.10.2024 </datum>
				<bezeichnung> Kursun </bezeichnung>
				<notiz> Topumdan siksinlar </notiz>
			</ereigniss>
		</ereignisse>

		<gruppen>
			<gruppe> </gruppe>
		</gruppen>
		
	</kontakt>

	<kontakt>

		<anrede> Herr </anrede>
		<titel> Reis </titel>
		<name> Bayramoglu </name>
		<vorname> Recep </vorname>
		<spitzname> Reco </spitzname>
		<geburtstag art="fake"> 22.01.1963 </geburtstag>
		<bild/> 

		<firma> 
			<name> Siemens </name>
			<abteilung> Liniensteuerung </abteilung>
			<position> Abteilungs Leiter </position>
		</firma>	

		<adresse>
			<strasse> Rosenheimer Str.80 </strasse>
			<plz> 81669 </plz>
			<ort> München </ort>
			<region> Bayern </region>
			<staat> Deutschland </staat>
		</adresse>

		<nummern art="firma"> 
			<nummer> 089555555 </nummer>
		</nummern>
		
		<mailadresse art="firma"> r.bayramoglu@siemens.de </mailadresse>
		<webadresse> </webadresse>
		<messenger> </messenger>

		<memo>
			<notiz> babu </notiz>
		</memo>

		<ereignisse>
			<ereigniss>
				<datum> 23.10.2024 </datum>
				<bezeichnung> Sinir Krisi </bezeichnung>
				<notiz> Karisi geliyo eyvah </notiz>
			</ereigniss>
		</ereignisse>

		<gruppen>
			<gruppe> Aile </gruppe>
		</gruppen>
		
	</kontakt>


</root>
